# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: git submodule init && git submodule update;
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build --workspaces --if-present
      - run:
          command: npm run test -- --testTimeout 35000 --runInBand
          name: Run tests
  lint:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: git submodule init && git submodule update;
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build --workspaces --if-present
      - run:
          command: npm run lint -- --max-warnings 0
          name: Lint
  typescript:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: git submodule init && git submodule update;
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build --workspaces --if-present
      - run:
          command: npm run typescript
          name: Typescript

workflows:
  test:
    jobs:
      - lint
      - test
      - typescript
